# Generated by Django 3.0.11 on 2021-02-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210208_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video_id',
            new_name='video_id',
        ),
    ]
