# Generated by Django 3.0.11 on 2021-02-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_payment_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
